Fix bug for reading source settings set by user
Nuclear-Verification-and-Disarmament/ONIX pull request #1
Opened 2022-01-21 14:54 UTC by jung-benjamin

Source settings specified by the user are now read correctly by onix and not overwritten with a point source.

2022-01-26 12:32 UTC, Rademacher requested changes
I would suggest leaving the point source in (0,0,0) as default settings in case no specific source is provided by the user, both for ease of use as well as backwards compatibility reasons. Possibly like this:

[_read_user_settings.txt](https://github.com/Nuclear-Verification-and-Disarmament/ONIX/files/7941687/_read_user_settings.txt)

2022-01-26 12:48 UTC, jung-benjamin commented
Good point about the backwards compatibility. 

It is possible to run eigenvalue calculations in OpenMC without specifying a source. Would it not be preferable to have the
defautl OpenMC functionality if one does not specify a source manually?

2022-01-26 14:57 UTC, Rademacher commented
After looking it up the openmc default source seems to in fact be a point source at the origin as well. So I suppose setting it here is not really necessary, though it would potentially help clarify things in case one isn't aware of this behaviour - I would personally leave it in. Even if we decide not to do so we would still need to check if there has been a user defined source to prevent the source._from_xml_element line from crashing though.

2022-01-26 15:25 UTC, Rademacher requested changes
source needs to be initialised as None to make it callable, otherwise the if-statement will just crash

2022-01-26 15:35 UTC, jung-benjamin commented
True, I totally forgot to add that.

2022-01-27 15:24 UTC, Rademacher approved these changes
Seems good now

2022-01-27 15:55 UTC, Rademacher approved these changes

2022-01-27 16:03 UTC, merged